### ISSUE TITLE
Bad cert

### ISSUE THREAD

**Issue by kasbah** [oManual/omanual-site#1]
Hey, the site force redirects to https but the cert isn't valid for [omanual.org](http://omanual.org) which means visitors are greeted with a scary warning. If you click more info you can see that the certificate is only valid for answers.e-arc.com and arcwiki.e-arc.com.

**Comment by kwiens** [comment]
You're right! We'll work on it.

**Comment by kasbah** [comment]
Is there some way I can help with this? A quick fix might be to do a static export of the site and put it on Github pages (where you will get a free auto-renewing cert).

**Comment by kwiens** [comment]
Sorry about that—I totally forgot to work on this. Thanks for the reminder, it's fixed now!
